#!/usr/bin/env bash
#
# Per-project provisioning hook. Called by backend-nest's
# ProjectAppProvisionService after the project repo lands at
# $WORKSPACE_DIR. PlayCode passes inputs as env vars (below);
# everything NixOS-specific lives here so the saga stays
# template-agnostic.
#
# Inputs:
#   PROJECT_NAME       - URL-safe slug
#   PROJECT_TITLE      - human-readable title
#   APP_PORT           - public TCP port the user-facing service binds
#   SPA_MODE           - "true" iff this provision came from a
#                        browser-import with files in frontend-spa/;
#                        flips which systemd unit serves /
#   WORKSPACE_DIR      - project root (e.g. /workspace)
#   APP_USER           - non-root user that owns the repo (e.g. app)
#   RUN_PNPM_INSTALL   - "yes" iff the saga added files post-bake and
#                        we need a fresh node_modules
#
# Required env vars are fatal-missing; sane defaults aren't this script's job.

set -euo pipefail

: "${PROJECT_NAME:?PROJECT_NAME is required}"
: "${PROJECT_TITLE:?PROJECT_TITLE is required}"
: "${APP_PORT:?APP_PORT is required}"
: "${SPA_MODE:?SPA_MODE is required (true|false)}"
: "${WORKSPACE_DIR:?WORKSPACE_DIR is required}"
: "${APP_USER:?APP_USER is required}"
RUN_PNPM_INSTALL="${RUN_PNPM_INSTALL:-no}"

cd "$WORKSPACE_DIR"
WORKSPACE_REAL_DIR="$(readlink -f "$WORKSPACE_DIR")"

EFFECTIVE_SPA_MODE="$SPA_MODE"
if [ "$EFFECTIVE_SPA_MODE" = "true" ] && [ ! -d "$WORKSPACE_DIR/frontend-spa" ]; then
  echo "WARN: SPA_MODE=true but frontend-spa/ is missing; falling back to Vike SSR frontend." >&2
  EFFECTIVE_SPA_MODE="false"
fi

# ── 1. Render nixos/project.nix from inputs ──────────────────────────────
# JSON-encoding name/title so a project containing a quote can't break
# out of the Nix string literal. JSON's escape set is a strict subset
# of Nix's; same escapes work in both. Pure-bash implementation -
# no python/jq dependency, works on any minimal NixOS bake.

json_str() {
  local s="$1"
  s="${s//\\/\\\\}"   # \ → \\
  s="${s//\"/\\\"}"   # " → \"
  s="${s//$'\n'/\\n}" # newline → \n
  s="${s//$'\t'/\\t}" # tab → \t
  s="${s//$'\r'/\\r}" # CR → \r
  printf '"%s"' "$s"
}

NAME_NIX=$(json_str "$PROJECT_NAME")
TITLE_NIX=$(json_str "$PROJECT_TITLE")

random_hex() {
  local bytes="$1"
  node -e "console.log(require('node:crypto').randomBytes(Number(process.argv[1])).toString('hex'))" "$bytes"
}

env_quote() {
  local s="$1"
  s="${s//$'\n'/ }"
  s="${s//$'\r'/ }"
  s="${s//\'/\'\\\'\'}"
  printf "'%s'" "$s"
}

env_has_key() {
  local key="$1"
  [ -f "$WORKSPACE_DIR/.env.local" ] && grep -qE "^${key}=" "$WORKSPACE_DIR/.env.local"
}

env_set_once() {
  local key="$1"
  local value="$2"
  if ! env_has_key "$key"; then
    printf '%s=%s\n' "$key" "$value" >> "$WORKSPACE_DIR/.env.local"
  fi
}

cat > "$WORKSPACE_DIR/nixos/project.nix" <<EOF
# Per-project values for ${PROJECT_TITLE}.
# AUTOGENERATED by templates/base-react/setup.sh at provision time.
# Manual edits survive until the next provision; for permanent changes,
# update setup.sh in the template.

{ config, lib, ... }:

{
  playcode = {
    project = {
      name = ${NAME_NIX};
      title = ${TITLE_NIX};
    };

    network = {
      appPort = ${APP_PORT};
      frontendPort = 3010;
      backendPort = 3011;
      staticPort = 3012;
    };

    services = {
      frontend.enable = true;
      backend.enable = true;
      spaMode = ${EFFECTIVE_SPA_MODE};
      mode = "dev";
    };

    database = {
      postgres.enable = true;
      redis.enable = true;
      postgres.password = "";
      redis.password = "";
    };
  };
}
EOF

# ── 1a. Generate per-project local secrets ───────────────────────────────
# `.env.local` is intentionally gitignored. Values are generated once and
# preserved across provision retries; rotating them would invalidate cookies,
# refresh tokens, password-reset links, and the app user's DB password.

touch "$WORKSPACE_DIR/.env.local"
chmod 600 "$WORKSPACE_DIR/.env.local"

env_set_once "POSTGRES_PASSWORD" "$(random_hex 32)"
POSTGRES_PASSWORD="$(grep -E '^POSTGRES_PASSWORD=' "$WORKSPACE_DIR/.env.local" | tail -1 | cut -d= -f2-)"
env_set_once "DATABASE_URL" "postgresql://app:${POSTGRES_PASSWORD}@127.0.0.1:5432/${PROJECT_NAME}"
env_set_once "REDIS_URL" "redis://127.0.0.1:6379"
env_set_once "JWT_ACCESS_SECRET" "$(random_hex 64)"
env_set_once "JWT_REFRESH_SECRET" "$(random_hex 64)"
env_set_once "JWT_ACCESS_TTL" "15m"
env_set_once "JWT_REFRESH_TTL" "30d"
env_set_once "AUTH_EXPOSE_ACCESS_TOKEN" "true"
env_set_once "AUTH_COOKIE_SAME_SITE" "lax"
env_set_once "ADMIN_EMAILS" ""
env_set_once "MAIL_TRANSPORT" "console"
env_set_once "MAIL_FROM" "$(env_quote "${PROJECT_TITLE} <noreply@example.com>")"
env_set_once "PUBLIC_URL" "http://localhost:${APP_PORT}"

# ── 1b. Substitute {{PROJECT_NAME}} / {{PROJECT_TITLE}} across source ────
# These two placeholders live in:
#   - frontend/package.json + backend-nest/package.json  (workspace names)
#   - frontend/pages/*.tsx + frontend/renderer/*.tsx     (visible UI)
#   - backend-nest/src/health.controller.ts              (/health response)
#   - backend-nest/src/auth/auth.service.ts              (password-reset email)
#   - backend-nest/src/config/config.service.ts          (MAIL_FROM default)
#   - prisma/schema.prisma + various .md                 (comments)
#
# Substitute in one find pass; node_modules + .git excluded. Runs BEFORE
# chown so the rewritten files inherit app ownership in the next step.

sed_escape() {
  # Escape sed-replacement metachars in human-input strings:
  # \ -> \\ (must be first), & -> \&, | -> \| (matches our delimiter).
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//&/\\&}"
  s="${s//|/\\|}"
  printf '%s' "$s"
}

SAFE_NAME=$(sed_escape "$PROJECT_NAME")
SAFE_TITLE=$(sed_escape "$PROJECT_TITLE")

find "$WORKSPACE_REAL_DIR" \
  -type f \
  \( -name '*.ts' -o -name '*.tsx' -o -name '*.json' -o -name '*.prisma' -o -name '*.md' \) \
  -not -path '*/node_modules/*' \
  -not -path '*/.git/*' \
  -exec sed -i \
    -e "s|{{PROJECT_NAME}}|${SAFE_NAME}|g" \
    -e "s|{{PROJECT_TITLE}}|${SAFE_TITLE}|g" \
    {} +

remaining_placeholders="$(
  find "$WORKSPACE_REAL_DIR" \
    -type f \
    \( -name '*.ts' -o -name '*.tsx' -o -name '*.json' -o -name '*.prisma' -o -name '*.md' \) \
    -not -path '*/node_modules/*' \
    -not -path '*/.git/*' \
    -exec grep -HnE '\{\{PROJECT_(NAME|TITLE)\}\}' {} + || true
)"

if [ -n "$remaining_placeholders" ]; then
  echo "FATAL: project placeholder substitution left unresolved values:" >&2
  printf '%s\n' "$remaining_placeholders" | head -40 >&2
  exit 1
fi

# ── 2. Fix ownership of paths the saga (root) just touched ───────────────
# sky-guest's /exec and /files endpoints run as root; anything the
# provisioning saga writes lands root-owned. The `app` user (which runs
# pnpm, systemd units, git) can't read root-owned files it didn't get
# explicit ACLs for. Used to be done in backend code (`chownAfterDump`);
# moved here in v2026.7.91 so the backend stays template-agnostic - it
# doesn't know that `frontend-spa/` or `docs/` even exist.
#
# Scoped tightly instead of `chown -R $WORKSPACE_DIR` - that recursion
# walks ~30k files in node_modules from the bake (already app-owned),
# costing ~1.3s for nothing. Listed paths cover everything the saga
# touches as root:
#   - /home/app + dotfiles  (ssh-keygen, deploy key)
#   - $WORKSPACE_DIR/.git  (git ops ran as root)
#   - $WORKSPACE_DIR/nixos/project.nix  (rewritten right above)
#   - $WORKSPACE_DIR/frontend-spa/  (browser-import wrote it, SPA_MODE=true)
#   - $WORKSPACE_DIR/docs/  (browser-import migration guide)

chown "${APP_USER}":"${APP_USER}" /home/app
chmod 755 /home/app
chown -R "${APP_USER}":"${APP_USER}" /home/app/.[!.]* 2>/dev/null || true
chown -R "${APP_USER}":"${APP_USER}" "$WORKSPACE_DIR/.git"
chown "${APP_USER}":"${APP_USER}" "$WORKSPACE_DIR/nixos/project.nix"
chown "${APP_USER}":"${APP_USER}" "$WORKSPACE_DIR/.env.local"
[ -d "$WORKSPACE_DIR/frontend-spa" ] && chown -R "${APP_USER}":"${APP_USER}" "$WORKSPACE_DIR/frontend-spa"
[ -d "$WORKSPACE_DIR/docs" ] && chown -R "${APP_USER}":"${APP_USER}" "$WORKSPACE_DIR/docs"

# ── 3. Commit project.nix (clean tree = faster nixos-rebuild) ────────────
# Dirty tree forces Nix to copy untracked files into /nix/store at eval
# time. The conditional commit is idempotent on re-runs.

git config --global --add safe.directory "$WORKSPACE_DIR"
git add nixos/project.nix
git diff --cached --quiet nixos/project.nix || \
  git commit -m 'apply per-project nix config' --quiet

# ── 4. Refresh node_modules BEFORE nixos-rebuild ─────────────────────────
# Order matters: nixos-rebuild's activation phase starts systemd units
# (notably `playcode-frontend-spa.service` when SPA_MODE=true). That unit
# runs `pnpm dev` and needs node_modules to exist. If we rebuilt first
# and installed after, the unit fails at activation and the whole
# rebuild exits 4.
#
# Bake-time pnpm install ran before any frontend-spa/ files were
# dumped, so its node_modules is missing the user's deps in that case.
# /etc/profile is sourced for NixOS-managed env vars (PRISMA_* etc.)
# that sudo would otherwise strip.

if [ "$RUN_PNPM_INSTALL" = "yes" ]; then
  cd "$WORKSPACE_DIR"
  sudo -u "$APP_USER" -H sh -c '. /etc/profile && cd '"$WORKSPACE_DIR"' && pnpm install --reporter=append-only' 2>&1 | tail -80
fi

# ── 5. Apply NixOS config ────────────────────────────────────────────────
# --fast skips re-checking Nix itself is current. Output trimmed because
# nixos-rebuild is verbose. node_modules is already in place from step 4
# so any unit it starts boots cleanly.
#
# Stop bake-time app units synchronously BEFORE rebuild. switch-to-
# configuration stops removed units in parallel with starting new ones,
# and the TCP listen sockets on 3010/3011/3012 don't release instantly
# when SIGTERM fires. Vite (with strictPort=true after this lands) will
# crash on bind; without strictPort it silently falls back to 3013 and
# Traefik 502s. Explicit synchronous stop here means the new units come
# up against fully-released ports. `|| true` so a missing/already-stopped
# unit doesn't fail set -e.
systemctl stop 'playcode-*.service' 2>/dev/null || true

cd "$WORKSPACE_DIR/nixos"
nixos-rebuild switch --flake .#default --fast 2>&1 | tail -120

# ── 5b. Release the bake gate and start app services ────────────────────
# Warm-template checkpoints are captured with .bake-mode present so forked
# user VMs do not start backend services with bake-time placeholder secrets.
# Provision creates per-user .env.local above, applies NixOS config, then
# releases the gate and starts the units.

rm -f "$WORKSPACE_DIR/.bake-mode"
if systemctl cat playcode-postgresql-configure-app.service >/dev/null 2>&1; then
  systemctl restart playcode-postgresql-configure-app.service
fi

# Units skipped by ConditionPathExists remain inactive after nixos-rebuild.
# Start expected app units explicitly after releasing .bake-mode; missing
# units are fine because SSR and SPA modes enable different frontend units.
for unit in playcode-frontend.service playcode-frontend-spa.service playcode-backend.service; do
  if systemctl cat "$unit" >/dev/null 2>&1; then
    systemctl reset-failed "$unit" 2>/dev/null || true
    systemctl start "$unit"
  fi
done

# ── 6. Self-delete - one-shot tool, not part of the user's repo ──────────
# Only runs if everything above succeeded (set -e at the top). On failure
# the script stays on disk so a retry can pick it up.
#
# Idempotent: rm -f no-ops when missing; --ignore-unmatch no-ops when
# the file isn't tracked; the conditional commit no-ops when nothing
# was staged. A retry that lands on step 6 a second time exits clean.

cd "$WORKSPACE_DIR"
rm -f setup.sh
git rm --cached --quiet --ignore-unmatch setup.sh
git diff --cached --quiet || \
  git commit -m 'provisioning: remove one-shot setup.sh' --quiet --author='PlayCode <noreply@playcode.io>'
chown -R "${APP_USER}":"${APP_USER}" "$WORKSPACE_DIR/.git"
