// Auto-generated by BrowserImportService for the legacy SPA build.
// Edit if you need to customize. Re-running setup will not overwrite
// once you delete the marker line below.
// BROWSER-IMPORT-GENERATED: replace this file to take ownership

import { defineConfig } from 'vite'
import tailwindcss from '@tailwindcss/vite'

export default defineConfig({
  plugins: [tailwindcss()],
  server: {
    host: '0.0.0.0',
    port: Number(process.env.PORT) || 5173,
    strictPort: true,
    allowedHosts: true,
    hmr: {
      protocol: 'wss',
      clientPort: 443,
    },
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    target: 'esnext',
  },
  // PlayCode browser projects never use process.env / import.meta.env
  // exposing them here would silently change runtime behavior. If
  // you need env vars after migrating, add them via Vite's standard
  // `define:` block here.
})
