# Per-project values for bouncebacktalk_app.
# AUTOGENERATED by templates/base-react/setup.sh at provision time.
# Manual edits survive until the next provision; for permanent changes,
# update setup.sh in the template.

{ config, lib, ... }:

{
  playcode = {
    project = {
      name = "playcode-bouncebacktalk-app";
      title = "bouncebacktalk_app";
    };

    network = {
      appPort = 3000;
      frontendPort = 3010;
      backendPort = 3011;
      staticPort = 3012;
    };

    services = {
      frontend.enable = true;
      backend.enable = true;
      spaMode = true;
      mode = "dev";
    };

    database = {
      postgres.enable = true;
      redis.enable = true;
      postgres.password = "";
      redis.password = "";
    };
  };
}
